In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = np.array([5, 6, 7, 8, 8])
print(a)

[5 6 7 8 8]


In [5]:
a[2]

7

In [6]:
a[1:4]

array([6, 7, 8])

In [7]:
a.dtype

dtype('int32')

In [9]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
b.shape

(2, 3)

In [11]:
b.ndim

2

In [12]:
b.size

6

In [26]:
c = np.array([
    [[1, 2, 3], 
     [4, 5, 6]], 
    
    [[7, 8, 9], 
     [10, 11, 12]]
])

In [16]:
c.shape

(2, 2, 3)

In [17]:
c[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
c[:, :, 0]

array([[ 1,  4],
       [ 7, 10]])

In [20]:
c.sum()    

78

In [21]:
c.std()

3.452052529534663

In [22]:
c.mean()

6.5

In [23]:
c.var()

11.916666666666666

In [24]:
c.sum(axis = 1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [25]:
c.sum(axis = 0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [27]:
c.sum(axis = 2)

array([[ 6, 15],
       [24, 33]])

In [28]:
d = np.arange(5)
d

array([0, 1, 2, 3, 4])

In [29]:
d = d + 10

In [30]:
d

array([10, 11, 12, 13, 14])

In [31]:
e = np.array([1, 2, 3, 4])
for i in e :
    print (i * 5)

5
10
15
20


In [32]:
f = np.arange(5)

In [34]:
f[[1, 3]]

array([1, 3])

In [36]:
f[[True, False, True, False, True]]

array([0, 2, 4])

In [37]:
f >= 4

array([False, False, False, False,  True])

In [38]:
g = f >= 3

In [39]:
g

array([False, False, False,  True,  True])

In [41]:
f[g]

array([3, 4])

In [44]:
f[f > f.mean()]

array([3, 4])

In [45]:
np.random.random(size = 2)

array([0.88829269, 0.84769365])

In [46]:
np.random.normal(size = 2)

array([-0.00624271,  0.69905165])

In [47]:
np.random.rand(2, 4)

array([[0.10174859, 0.44919202, 0.21506627, 0.00744797],
       [0.92264255, 0.61787238, 0.52585639, 0.85462578]])

In [49]:
np.zeros([1, 2])

array([[0., 0.]])

In [50]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])